### ISSUE TITLE
Low cpu usage when doing obj2mesh

### ISSUE THREAD

**Issue by StarRealMan** [g3956/PRM#2]
Thank you for your great work.
Recently, I'm doing obj2mesh preprocess using obj2mesh.py. However, I find that the cpu usage is pretty low and it takes a long time to finish. I let chatgpt to refine the code from multi-thread to multi-process and it gets better.

**Comment by LTT-O** [comment]
> Thank you for your great work. Recently, I'm doing obj2mesh preprocess using obj2mesh.py. However, I find that the cpu usage is pretty low and it takes a long time to finish. I let chatgpt to refine the code from multi-thread to multi-process and it gets better.

Thank you for bringing this up and for using obj2mesh.py! I’m glad to hear that switching from multi-threading to multi-processing improved the performance.

The low CPU usage you initially experienced is likely due to the Global Interpreter Lock (GIL) in Python, which can limit the effectiveness of multi-threading for CPU-bound tasks like this one. Switching to multi-processing is a great way to bypass the GIL and take better advantage of multiple CPU cores.

I’ll review the code and see if further optimizations or enhancements can be made to improve efficiency. If you’ve already made changes to use multi-processing, feel free to submit a pull request so others in the community can benefit from your improvement.

Thank you for your feedback and for helping to make this project better!
